#!/usr/bin/env bash
set -euo pipefail

root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
cd "$root"
tmp_dir=${TMPDIR:-/tmp}
runtime_dir=$(mktemp -d "${tmp_dir%/}/ec2-environment-install.XXXXXX")
trap 'rm -rf "$runtime_dir"' EXIT
mock_bin="$runtime_dir/bin"
xdg_config="$runtime_dir/config"
environment_config="$xdg_config/ec2/environment"
aws_log="$runtime_dir/aws.log"
mkdir -p "$mock_bin" "$(dirname "$environment_config")"

cat > "$mock_bin/aws" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "$AWS_LOG"
if [[ " $* " == *" ec2 describe-images "* ]];then
  echo ami-environment-install-test
fi
EOF
chmod 755 "$mock_bin/aws"

cat > "$environment_config" <<'EOF'
AWS_REGION=ap-northeast-1
CPU_OUTPUT_AMI_NAME=environment-install-test
AWS_SUBNET_IDS=subnet-environment-install-test
EC2_SUBNET_LABELS=ci
EC2_KEY_NAME=environment-install-test
EC2_SSH_OPTIONS=(-o StrictHostKeyChecking=no)
EC2_ET_OPTIONS=(--keepalive 30 --terminal-path '/opt/et terminal')
EC2_SCP_OPTIONS=(-r -p)
EC2_RSYNC_OPTIONS=(-a --delete '--exclude=cache dir')
USER_ENV_ENABLE_USR_SYMLINK=0
USER_ENV_DOTFILES_FILE=
USER_ENV_DOTFILES_DIR=
EOF

echo 'manual_setting=keep-me' > "$xdg_config/ec2/config"
if HOME="$runtime_dir/home" XDG_CONFIG_HOME="$xdg_config" AWS_LOG="$aws_log" \
  PATH="$mock_bin:$PATH" bin/ec2 setup >/dev/null 2>&1;then
  echo 'setup must refuse an unmanaged default ec2 config.' >&2
  exit 1
fi
[[ ! -s "$aws_log" ]] || {
  echo 'setup must check the destination config before calling AWS.' >&2
  exit 1
}

HOME="$runtime_dir/home" XDG_CONFIG_HOME="$xdg_config" AWS_LOG="$aws_log" \
  PATH="$mock_bin:$PATH" bin/ec2 setup --replace-config 1 >/dev/null

installed="$xdg_config/ec2/config"
generated="$xdg_config/ec2/work/ec2/config"
[[ -f "$installed" && -f "$generated" ]]
cmp -s "$installed" "$generated"
grep -q '^# Generated by ec2 setup\.$' "$installed"
grep -q "^ssh_key=''$" "$installed"
bash -c '
  set -euo pipefail
  source "$1"
  [[ ${#ssh_option[@]} == 2 ]]
  [[ ${ssh_option[0]} == -o ]]
  [[ ${ssh_option[1]} == StrictHostKeyChecking=no ]]
  [[ ${#et_option[@]} == 4 ]]
  [[ ${et_option[0]} == --keepalive ]]
  [[ ${et_option[1]} == 30 ]]
  [[ ${et_option[2]} == --terminal-path ]]
  [[ ${et_option[3]} == "/opt/et terminal" ]]
  [[ ${#scp_option[@]} == 2 ]]
  [[ ${scp_option[0]} == -r ]]
  [[ ${scp_option[1]} == -p ]]
  [[ ${#rsync_option[@]} == 3 ]]
  [[ ${rsync_option[0]} == -a ]]
  [[ ${rsync_option[1]} == --delete ]]
  [[ ${rsync_option[2]} == "--exclude=cache dir" ]]
' _ "$installed"
grep -q "cli_input_json_directory=$xdg_config/ec2/work/ec2/cli_input_json" "$installed"
grep -q "user_data=fileb://$xdg_config/ec2/work/ec2/user_data.sh.gz" "$installed"
[[ $(stat -f '%Lp' "$installed" 2>/dev/null || stat -c '%a' "$installed") == 600 ]]

mapfile -t backups < <(printf '%s\n' "$xdg_config"/ec2/config.backup-*)
[[ ${#backups[@]} == 1 && -f "${backups[0]}" ]]
grep -q '^manual_setting=keep-me$' "${backups[0]}"

HOME="$runtime_dir/home" XDG_CONFIG_HOME="$xdg_config" AWS_LOG="$aws_log" \
  PATH="$mock_bin:$PATH" bin/ec2 setup >/dev/null
mapfile -t backups_after < <(printf '%s\n' "$xdg_config"/ec2/config.backup-*)
[[ ${#backups_after[@]} == 1 ]]

external_config="$runtime_dir/external-config"
echo 'external_setting=keep-me' > "$external_config"
rm "$installed"
ln -s "$external_config" "$installed"
: > "$aws_log"
if HOME="$runtime_dir/home" XDG_CONFIG_HOME="$xdg_config" AWS_LOG="$aws_log" \
  PATH="$mock_bin:$PATH" bin/ec2 setup >/dev/null 2>&1;then
  echo 'setup must refuse a symbolic-link default ec2 config.' >&2
  exit 1
fi
[[ ! -s "$aws_log" ]] || {
  echo 'setup must reject a config symlink before calling AWS.' >&2
  exit 1
}
HOME="$runtime_dir/home" XDG_CONFIG_HOME="$xdg_config" AWS_LOG="$aws_log" \
  PATH="$mock_bin:$PATH" bin/ec2 setup --replace-config 1 >/dev/null
[[ -f "$installed" && ! -L "$installed" ]]
grep -q '^external_setting=keep-me$' "$external_config"
mapfile -t final_backups < <(printf '%s\n' "$xdg_config"/ec2/config.backup-*)
[[ ${#final_backups[@]} == 2 ]]

echo 'Environment config installation tests passed.'
