# shellcheck shell=bash
# shellcheck disable=SC2154

_environment_runtime() {
  local script=$1
  shift
  (
    set -e
    local runtime
    runtime=$(mktemp -d "${TMPDIR:-/tmp}/ec2-environment.XXXXXX")
    trap 'command rm -rf "$runtime"' EXIT
    _environment_extract "$runtime"
    "$runtime/scripts/$script" "$@"
  )
}

_environment_args() {
  __environment_command_workdir="${__positional[0]:-$__workdir}"
  __environment_command_config="${__positional[1]:-$__environment_config}"
}

_environment_config_is_managed() {
  [ -f "$1" ] && grep -q '^# Generated by ec2 setup\.$' "$1"
}

_environment_preflight_config() {
  [ "$__install_config" = "1" ] || return 0

  if [ -L "$__default_config" ];then
    if [ "$__replace_config" != "1" ];then
      echo "Refusing to replace symbolic link: $__default_config" >&2
      echo "Use --replace-config 1 to back it up and install the generated config." >&2
      return 1
    fi
  elif [ -e "$__default_config" ] && ! _environment_config_is_managed "$__default_config" && [ "$__replace_config" != "1" ];then
    echo "Refusing to replace unmanaged configuration: $__default_config" >&2
    echo "Use --replace-config 1 to back it up and install the generated config." >&2
    return 1
  fi
}

_environment_install_config() {
  local generated=$1
  [ "$__install_config" = "1" ] || {
    echo "Generated $generated (not installed because --install-config is not 1)."
    return 0
  }
  [ -s "$generated" ] || {
    echo "Generated configuration is missing or empty: $generated" >&2
    return 1
  }
  _environment_config_is_managed "$generated" || {
    echo "Generated configuration has no ec2 setup management marker: $generated" >&2
    return 1
  }

  mkdir -p "$__config_dir"
  chmod 700 "$__config_dir"

  if [ -f "$__default_config" ] && [ ! -L "$__default_config" ] && cmp -s "$generated" "$__default_config";then
    echo "Configuration is already current: $__default_config"
    return 0
  fi

  if [ -e "$__default_config" ] || [ -L "$__default_config" ];then
    if ! _environment_config_is_managed "$__default_config";then
      local backup
      backup="${__default_config}.backup-$(date +%Y%m%d-%H%M%S)"
      [ ! -e "$backup" ] && [ ! -L "$backup" ] || backup="${backup}.$$"
      mv "$__default_config" "$backup"
      echo "Backed up existing configuration to $backup"
    fi
  fi

  local temporary="${__default_config}.tmp.$$"
  command rm -f "$temporary"
  if ! cp "$generated" "$temporary";then
    command rm -f "$temporary"
    return 1
  fi
  if ! chmod 600 "$temporary" || ! mv -f "$temporary" "$__default_config";then
    command rm -f "$temporary"
    return 1
  fi
  echo "Installed ec2 configuration: $__default_config"
}

_environment_cleanup_args() {
  __environment_cleanup_args=(--workdir "$__environment_command_workdir" --config "$__environment_command_config")
  [ -z "$__manifest" ] || __environment_cleanup_args+=(--manifest "$__manifest")
  [ "$__execute" != "1" ] || __environment_cleanup_args+=(--execute)
}

make_ami() {
  # Build the configured EC2 AMIs with Packer.
  _environment_args
  _environment_runtime make_ami "$__environment_command_workdir" "$__environment_command_config"
}

setup() {
  # Generate EC2 launch inputs and install the default ec2 configuration.
  _environment_args
  _environment_preflight_config || return 1
  _environment_runtime setup_ec2 "$__environment_command_workdir" "$__environment_command_config" || return
  _environment_install_config "$__environment_command_workdir/ec2/config"
}

setup_efs() {
  # Resolve or create configured EFS file systems.
  _environment_args
  _environment_runtime setup_efs "$__environment_command_workdir" "$__environment_command_config"
}

setup_fsx() {
  # Resolve or create configured FSx file systems.
  _environment_args
  _environment_runtime setup_fsx "$__environment_command_workdir" "$__environment_command_config"
}

setup_io2() {
  # Resolve or create configured io2 volumes.
  _environment_args
  _environment_runtime setup_io2 "$__environment_command_workdir" "$__environment_command_config"
}

setup_s3files() {
  # Resolve configured S3 file-system identifiers.
  _environment_args
  _environment_runtime setup_s3files "$__environment_command_workdir" "$__environment_command_config"
}

cleanup_resources() {
  # Show or execute cleanup for resources recorded by environment commands.
  _environment_args
  _environment_cleanup_args
  _environment_runtime cleanup_resources "${__environment_cleanup_args[@]}"
}

init_environment() {
  # Install an example environment configuration without overwriting one.
  if [ -e "$__environment_config" ] || [ -L "$__environment_config" ];then
    echo "Environment configuration already exists: $__environment_config" >&2
    return 1
  fi
  (
    set -e
    local runtime temporary
    runtime=$(mktemp -d "${TMPDIR:-/tmp}/ec2-environment.XXXXXX")
    trap 'command rm -rf "$runtime"' EXIT
    _environment_extract "$runtime"
    mkdir -p "$(dirname "$__environment_config")"
    temporary="${__environment_config}.tmp.$$"
    cp "$runtime/config.example" "$temporary"
    chmod 600 "$temporary"
    mv "$temporary" "$__environment_config"
  )
  echo "Installed environment configuration: $__environment_config"
}
