#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: render-environment.sh --profile quickstart|advanced --region REGION \
  --stack-name NAME --state-dir DIR
EOF
}

profile=''
region="${AWS_REGION-}"
stack_name=''
state_dir=''
while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile) profile=$2; shift 2;;
    --region) region=$2; shift 2;;
    --stack-name) stack_name=$2; shift 2;;
    --state-dir) state_dir=$2; shift 2;;
    -h|--help) usage; exit 0;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2;;
  esac
done

[[ "$profile" == quickstart || "$profile" == advanced ]] || {
  echo '--profile must be quickstart or advanced.' >&2; exit 2;
}
[[ -n "$region" && -n "$stack_name" && -n "$state_dir" ]] || {
  echo '--region, --stack-name, and --state-dir are required.' >&2; exit 2;
}

stack_output() {
  local key=$1
  aws --region "$region" cloudformation describe-stacks \
    --stack-name "$stack_name" \
    --query "Stacks[0].Outputs[?OutputKey=='$key'].OutputValue | [0]" \
    --output text
}

mkdir -p "$state_dir"
key_name=$(stack_output KeyName)
profile_name=$(stack_output InstanceProfileName)
security_group_id=$(stack_output Ec2SecurityGroupId)
filesystem_id=$(stack_output FileSystemId)
public_subnet_id=''
if [[ "$profile" == quickstart ]]; then
  subnet_ids=$(stack_output SubnetId)
  mount_point=/mnt/efs
  root_dir=/mnt/efs/ec2
  associate_public_ip=true
  use_private_ip=0
  build_setting='AMI_BUILD_SSH_INTERFACE="public_ip"'
  security_group_setting="AWS_SECURITY_GROUP_IDS=\"$security_group_id\""
  printf -v filesystem_setting 'EFS_IDS="%s"\nEFS_MOUNT_POINTS="%s"' "$filesystem_id" "$mount_point"
  extra_setting=''
else
  public_subnet_id=$(stack_output PublicSubnetId)
  work_subnet_ids=$(stack_output WorkSubnetIds)
  job_subnet_ids=$(stack_output JobSubnetIds)
  subnet_ids="$work_subnet_ids"
  mount_point=/mnt/fsx
  root_dir=/mnt/fsx/ec2
  associate_public_ip=false
  use_private_ip=1
  build_setting=''
  security_group_setting="AWS_SECURITY_GROUP_IDS=\"$security_group_id\""
  printf -v filesystem_setting 'FSX_IDS="%s"\nFSX_MOUNT_POINTS="%s"\nFSX_DEPLOYMENT_TYPE="MULTI_AZ_1"\nFSX_ROUTE_TABLE_IDS=""' "$filesystem_id" "$mount_point"
  printf -v extra_setting 'AMI_BUILD_SUBNET_ID="%s"\nAMI_BUILD_SSH_INTERFACE="public_ip"\nEC2_SUBNET_LABELS="work-a,work-b"' "$public_subnet_id"
  printf 'JOB_SUBNET_IDS=%q\n' "$job_subnet_ids" > "$state_dir/job-subnets.env"
fi

cat > "$state_dir/environment" <<EOF
# Generated by examples/cloudformation/render-environment.sh.
AWS_REGION="$region"
RESOURCE_NAME_PREFIX="ec2-$profile"
AWS_SUBNET_IDS="$subnet_ids"
$security_group_setting
AWS_IAM_INSTANCE_PROFILE="$profile_name"
EC2_KEY_NAME="$key_name"
EC2_SSH_PRIVATE_KEY="$state_dir/id_ed25519"
EC2_CONNECTION_METHOD="ssm"
EC2_ASSOCIATE_PUBLIC_IP=$associate_public_ip
EC2_USE_PRIVATE_IP=$use_private_ip
EC2_DEFAULT_INSTANCE_TYPE="t3.medium"
CPU_BUILD_INSTANCE_TYPE="t3.medium"
CPU_OUTPUT_AMI_NAME="ec2-$profile-cpu-1"
CPU_ENABLED=1
GPU_ENABLED=0
CREATE_FILE_SYSTEMS=0
USER_ENV_ROOT_DIR="$root_dir"
$build_setting
$filesystem_setting
$extra_setting
EOF

if [[ "$profile" == advanced ]]; then
  sed \
    -e "s|^AWS_SUBNET_IDS=.*|AWS_SUBNET_IDS=\"$job_subnet_ids\"|" \
    -e 's|^EC2_SUBNET_LABELS=.*|EC2_SUBNET_LABELS="job-a,job-b"|' \
    "$state_dir/environment" > "$state_dir/environment-job"
  chmod 600 "$state_dir/environment-job"
fi

printf 'AWS_REGION=%q\nSTACK_NAME=%q\nKEY_NAME=%q\nINSTANCE_PROFILE=%q\nSECURITY_GROUP_ID=%q\nFILESYSTEM_ID=%q\nENVIRONMENT_FILE=%q\n' \
  "$region" "$stack_name" "$key_name" "$profile_name" "$security_group_id" "$filesystem_id" "$state_dir/environment" \
  > "$state_dir/outputs.env"
chmod 600 "$state_dir/outputs.env" "$state_dir/environment"
printf 'Generated %s\n' "$state_dir/environment"
