#!/usr/bin/env bash
set -e

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <base_dir> <prefix> <version>"
    exit 1
fi

base="$1"
prefix="$2"
version="$3"

if [ -f "$prefix/bin/screen" ];then
  echo "screen is already installed"
  exit 0
fi

dest="$base/screen"
mkdir -p "$dest"

tgz="screen-${version}.tar.gz"
curl -LO "https://ftp.gnu.org/gnu/screen/$tgz"
tar xvzf "$tgz" --strip-components 1 -C "$dest"
rm -f "$tgz"
cd "$dest"
./autogen.sh
./configure --prefix="$prefix"
make
make install
