#!/usr/bin/env bash
set -e

if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
    echo "Usage: $0 <base_dir> <prefix> [ref]"
    exit 1
fi

base="$1"
prefix="$2"
ref="${3:-main}"

if [ -f "$prefix/bin/ec2" ]; then
  echo "ec2 is already installed"
  exit 0
fi

mkdir -p "$base/ec2"

curl --fail --silent --show-error --location \
  "https://raw.githubusercontent.com/rcmdnk/ec2/$ref/bin/ec2" \
  -o "$base/ec2/ec2"
chmod 755 "$base/ec2/ec2"

mkdir -p "$prefix/bin"
cd "$prefix/bin"
ln -s "$base/ec2/ec2" ec2
